import { CircuitFE } from "../../types/CircruitFE";

export default function Circuits(): CircuitFE[] {
  return [
    {
      key: "1",
      circuitId: "albert_park",
      name: "Albert Park Grand Prix Circuit",
      location: "Melbourne",
      country: "Australia",
      imagen: true,
    },
    {
      key: "2",
      circuitId: "sepang",
      name: "Sepang International Circuit",
      location: "Kuala Lumpur",
      country: "Malaysia",
      imagen: null,
    },
    {
      key: "3",
      circuitId: "bahrain",
      name: "Bahrain International Circuit",
      location: "Sakhir",
      country: "Bahrain",
      imagen: true,
    },
    {
      key: "4",
      circuitId: "catalunya",
      name: "Circuit de Barcelona-Catalunya",
      location: "Montmeló",
      country: "Spain",
      imagen: true,
    },
    {
      key: "5",
      circuitId: "istanbul",
      name: "Istanbul Park",
      location: "Istanbul",
      country: "Turkey",
      imagen: true,
    },
    {
      key: "6",
      circuitId: "monaco",
      name: "Circuit de Monaco",
      location: "Monte-Carlo",
      country: "Monaco",
      imagen: true,
    },
    {
      key: "7",
      circuitId: "villeneuve",
      name: "Circuit Gilles Villeneuve",
      location: "Montreal",
      country: "Canada",
      imagen: null,
    },
    {
      key: "8",
      circuitId: "magny_cours",
      name: "Circuit de Nevers Magny-Cours",
      location: "Magny Cours",
      country: "France",
      imagen: null,
    },
    {
      key: "9",
      circuitId: "silverstone",
      name: "Silverstone Circuit",
      location: "Silverstone",
      country: "UK",
      imagen: true,
    },
    {
      key: "10",
      circuitId: "hockenheimring",
      name: "Hockenheimring",
      location: "Hockenheim",
      country: "Germany",
      imagen: null,
    },
    {
      key: "11",
      circuitId: "hungaroring",
      name: "Hungaroring",
      location: "Budapest",
      country: "Hungary",
      imagen: true,
    },
    {
      key: "12",
      circuitId: "valencia",
      name: "Valencia Street Circuit",
      location: "Valencia",
      country: "Spain",
      imagen: null,
    },
    {
      key: "13",
      circuitId: "spa",
      name: "Circuit de Spa-Francorchamps",
      location: "Spa",
      country: "Belgium",
      imagen: true,
    },
    {
      key: "14",
      circuitId: "monza",
      name: "Autodromo Nazionale di Monza",
      location: "Monza",
      country: "Italy",
      imagen: true,
    },
    {
      key: "15",
      circuitId: "marina_bay",
      name: "Marina Bay Street Circuit",
      location: "Marina Bay",
      country: "Singapore",
      imagen: null,
    },
    {
      key: "16",
      circuitId: "fuji",
      name: "Fuji Speedway",
      location: "Oyama",
      country: "Japan",
      imagen: null,
    },
    {
      key: "17",
      circuitId: "shanghai",
      name: "Shanghai International Circuit",
      location: "Shanghai",
      country: "China",
      imagen: true,
    },
    {
      key: "18",
      circuitId: "interlagos",
      name: "Autódromo José Carlos Pace",
      location: "São Paulo",
      country: "Brazil",
      imagen: null,
    },
    {
      key: "19",
      circuitId: "indianapolis",
      name: "Indianapolis Motor Speedway",
      location: "Indianapolis",
      country: "USA",
      imagen: null,
    },
    {
      key: "20",
      circuitId: "nurburgring",
      name: "Nürburgring",
      location: "Nürburg",
      country: "Germany",
      imagen: true,
    },
    {
      key: "21",
      circuitId: "imola",
      name: "Autodromo Enzo e Dino Ferrari",
      location: "Imola",
      country: "Italy",
      imagen: true,
    },
    {
      key: "22",
      circuitId: "suzuka",
      name: "Suzuka Circuit",
      location: "Suzuka",
      country: "Japan",
      imagen: null,
    },
    {
      key: "80",
      circuitId: "vegas",
      name: "Las Vegas Strip Street Circuit",
      location: "Las Vegas",
      country: "United States",
      imagen: null,
    },
    {
      key: "24",
      circuitId: "yas_marina",
      name: "Yas Marina Circuit",
      location: "Abu Dhabi",
      country: "UAE",
      imagen: true,
    },
    {
      key: "25",
      circuitId: "galvez",
      name: "Autódromo Juan y Oscar Gálvez",
      location: "Buenos Aires",
      country: "Argentina",
      imagen: null,
    },
    {
      key: "26",
      circuitId: "jerez",
      name: "Circuito de Jerez",
      location: "Jerez de la Frontera",
      country: "Spain",
      imagen: null,
    },
    {
      key: "27",
      circuitId: "estoril",
      name: "Autódromo do Estoril",
      location: "Estoril",
      country: "Portugal",
      imagen: null,
    },
    {
      key: "28",
      circuitId: "okayama",
      name: "Okayama International Circuit",
      location: "Okayama",
      country: "Japan",
      imagen: null,
    },
    {
      key: "29",
      circuitId: "adelaide",
      name: "Adelaide Street Circuit",
      location: "Adelaide",
      country: "Australia",
      imagen: null,
    },
    {
      key: "30",
      circuitId: "kyalami",
      name: "Kyalami",
      location: "Midrand",
      country: "South Africa",
      imagen: null,
    },
    {
      key: "31",
      circuitId: "donington",
      name: "Donington Park",
      location: "Castle Donington",
      country: "UK",
      imagen: null,
    },
    {
      key: "32",
      circuitId: "rodriguez",
      name: "Autódromo Hermanos Rodríguez",
      location: "Mexico City",
      country: "Mexico",
      imagen: null,
    },
    {
      key: "33",
      circuitId: "phoenix",
      name: "Phoenix street circuit",
      location: "Phoenix",
      country: "USA",
      imagen: null,
    },
    {
      key: "34",
      circuitId: "ricard",
      name: "Circuit Paul Ricard",
      location: "Le Castellet",
      country: "France",
      imagen: true,
    },
    {
      key: "35",
      circuitId: "yeongam",
      name: "Korean International Circuit",
      location: "Yeongam County",
      country: "Korea",
      imagen: null,
    },
    {
      key: "36",
      circuitId: "jacarepagua",
      name: "Autódromo Internacional Nelson Piquet",
      location: "Rio de Janeiro",
      country: "Brazil",
      imagen: null,
    },
    {
      key: "37",
      circuitId: "detroit",
      name: "Detroit Street Circuit",
      location: "Detroit",
      country: "USA",
      imagen: null,
    },
    {
      key: "38",
      circuitId: "brands_hatch",
      name: "Brands Hatch",
      location: "Kent",
      country: "UK",
      imagen: null,
    },
    {
      key: "39",
      circuitId: "zandvoort",
      name: "Circuit Park Zandvoort",
      location: "Zandvoort",
      country: "Netherlands",
      imagen: null,
    },
    {
      key: "40",
      circuitId: "zolder",
      name: "Zolder",
      location: "Heusden-Zolder",
      country: "Belgium",
      imagen: null,
    },
    {
      key: "41",
      circuitId: "dijon",
      name: "Dijon-Prenois",
      location: "Dijon",
      country: "France",
      imagen: null,
    },
    {
      key: "42",
      circuitId: "dallas",
      name: "Fair Park",
      location: "Dallas",
      country: "USA",
      imagen: null,
    },
    {
      key: "43",
      circuitId: "long_beach",
      name: "Long Beach",
      location: "California",
      country: "USA",
      imagen: null,
    },
    {
      key: "44",
      circuitId: "las_vegas",
      name: "Las Vegas Street Circuit",
      location: "Nevada",
      country: "USA",
      imagen: null,
    },
    {
      key: "45",
      circuitId: "jarama",
      name: "Jarama",
      location: "Madrid",
      country: "Spain",
      imagen: null,
    },
    {
      key: "46",
      circuitId: "watkins_glen",
      name: "Watkins Glen",
      location: "New York State",
      country: "USA",
      imagen: null,
    },
    {
      key: "47",
      circuitId: "anderstorp",
      name: "Scandinavian Raceway",
      location: "Anderstorp",
      country: "Sweden",
      imagen: null,
    },
    {
      key: "48",
      circuitId: "mosport",
      name: "Mosport International Raceway",
      location: "Ontario",
      country: "Canada",
      imagen: null,
    },
    {
      key: "49",
      circuitId: "montjuic",
      name: "Montjuïc",
      location: "Barcelona",
      country: "Spain",
      imagen: null,
    },
    {
      key: "50",
      circuitId: "nivelles",
      name: "Nivelles-Baulers",
      location: "Brussels",
      country: "Belgium",
      imagen: null,
    },
    {
      key: "51",
      circuitId: "charade",
      name: "Charade Circuit",
      location: "Clermont-Ferrand",
      country: "France",
      imagen: null,
    },
    {
      key: "52",
      circuitId: "tremblant",
      name: "Circuit Mont-Tremblant",
      location: "Quebec",
      country: "Canada",
      imagen: null,
    },
    {
      key: "53",
      circuitId: "essarts",
      name: "Rouen-Les-Essarts",
      location: "Rouen",
      country: "France",
      imagen: null,
    },
    {
      key: "54",
      circuitId: "lemans",
      name: "Le Mans",
      location: "Le Mans",
      country: "France",
      imagen: null,
    },
    {
      key: "55",
      circuitId: "reims",
      name: "Reims-Gueux",
      location: "Reims",
      country: "France",
      imagen: null,
    },
    {
      key: "56",
      circuitId: "george",
      name: "Prince George Circuit",
      location: "Eastern Cape Province",
      country: "South Africa",
      imagen: null,
    },
    {
      key: "57",
      circuitId: "zeltweg",
      name: "Zeltweg",
      location: "Styria",
      country: "Austria",
      imagen: null,
    },
    {
      key: "58",
      circuitId: "aintree",
      name: "Aintree",
      location: "Liverpool",
      country: "UK",
      imagen: null,
    },
    {
      key: "59",
      circuitId: "boavista",
      name: "Circuito da Boavista",
      location: "Oporto",
      country: "Portugal",
      imagen: null,
    },
    {
      key: "60",
      circuitId: "riverside",
      name: "Riverside International Raceway",
      location: "California",
      country: "USA",
      imagen: null,
    },
    {
      key: "61",
      circuitId: "avus",
      name: "AVUS",
      location: "Berlin",
      country: "Germany",
      imagen: null,
    },
    {
      key: "62",
      circuitId: "monsanto",
      name: "Monsanto Park Circuit",
      location: "Lisbon",
      country: "Portugal",
      imagen: null,
    },
    {
      key: "63",
      circuitId: "sebring",
      name: "Sebring International Raceway",
      location: "Florida",
      country: "USA",
      imagen: null,
    },
    {
      key: "64",
      circuitId: "ain-diab",
      name: "Ain Diab",
      location: "Casablanca",
      country: "Morocco",
      imagen: null,
    },
    {
      key: "65",
      circuitId: "pescara",
      name: "Pescara Circuit",
      location: "Pescara",
      country: "Italy",
      imagen: null,
    },
    {
      key: "66",
      circuitId: "bremgarten",
      name: "Circuit Bremgarten",
      location: "Bern",
      country: "Switzerland",
      imagen: null,
    },
    {
      key: "67",
      circuitId: "pedralbes",
      name: "Circuit de Pedralbes",
      location: "Barcelona",
      country: "Spain",
      imagen: null,
    },
    {
      key: "68",
      circuitId: "buddh",
      name: "Buddh International Circuit",
      location: "Uttar Pradesh",
      country: "India",
      imagen: null,
    },
    {
      key: "69",
      circuitId: "americas",
      name: "Circuit of the Americas",
      location: "Austin",
      country: "USA",
      imagen: null,
    },
    {
      key: "70",
      circuitId: "red_bull_ring",
      name: "Red Bull Ring",
      location: "Spielberg",
      country: "Austria",
      imagen: true,
    },
    {
      key: "71",
      circuitId: "sochi",
      name: "Sochi Autodrom",
      location: "Sochi",
      country: "Russia",
      imagen: true,
    },
    {
      key: "73",
      circuitId: "baku",
      name: "Baku City Circuit",
      location: "Baku",
      country: "Azerbaijan",
      imagen: null,
    },
    {
      key: "75",
      circuitId: "portimao",
      name: "Autódromo Internacional do Algarve",
      location: "Portimão",
      country: "Portugal",
      imagen: true,
    },
    {
      key: "76",
      circuitId: "mugello",
      name: "Autodromo Internazionale del Mugello",
      location: "Mugello",
      country: "Italy",
      imagen: true,
    },
    {
      key: "77",
      circuitId: "jeddah",
      name: "Jeddah Corniche Circuit",
      location: "Jeddah",
      country: "Saudi Arabia",
      imagen: true,
    },
    {
      key: "78",
      circuitId: "losail",
      name: "Losail International Circuit",
      location: "Al Daayen",
      country: "Qatar",
      imagen: null,
    },
    {
      key: "79",
      circuitId: "miami",
      name: "Miami International Autodrome",
      location: "Miami",
      country: "USA",
      imagen: null,
    },
  ];
}
